import StoryblokProvider from '@/components/StoryblokProvider';

export const metadata = {
	title: 'Coastline Kollektive',
	description: 'Generated by create next app',
	favIcon: '/favicon.ico',
};

export default function RootLayout({ children }) {
	return (
		<StoryblokProvider>
			<html lang="en">
				<body>{children}</body>
			</html>
		</StoryblokProvider>
	);
}
